### ISSUE TITLE
Regex matching negative scores

### ISSUE THREAD

**Issue by jzpero** [PoonLab/sierra-local#10]
Does anyone good with regex know how to capture negative integers as part of a string?
The current expression is: `scores = re.findall('[0-9]+(?=\W)', drm.strip())`, which captures only the positive numbers in the drug resistance mutation string. However, this excludes the negative scores which is the last barrier I'm encountering to producing validated results.

Example content which I need to extract `'-10'`, among the other numbers from:
![image](https://user-images.githubusercontent.com/5045614/32680711-f39bbb94-c639-11e7-8725-52bca4673572.png)

**Comment by jzpero** [comment]
Nevermind--read some docs

**Comment by ArtPoon** [comment]
FWIW, something like
```python
scores = re.findall('-*[0-9]+', drm.strip())
```
should do it
