### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by raquelriyuzo** [PoonLab/sierra-local#103]
Hello, I've noticed that the main branch was updated 3 months ago (Merge pull request #102 from PoonLab/dev), however, the last release v0.3 is from September/2023. Do you have any plans to generate a new release with this update? It would be important for us, who use sierra-local, to have it documented. 
Thank you very much!

**Comment by ArtPoon** [comment]
Hi @raquelriyuzo - thanks for pointing that out.  I'll draft a new release

**Comment by ArtPoon** [comment]
Released as v0.4.  Sorry I'm not on top of drafting releases - I tend to neglect this and focus on issues and PRs
