### ISSUE TITLE
Classification of mutations (to-do)

### ISSUE THREAD

**Issue by jzpero** [PoonLab/sierra-local#12]
From [HIVdb FAQ](https://hivdb.stanford.edu/pages/FAQ/FAQ_answers.html):

> The HIV Drug Resistance Database uses several different classification schemes. The HIVdb program and several of the query pages (such as detailed treatment queries, detailed mutation queries, advanced queries, detailed phenotype queries, and reference page) use a 3-way classification scheme that classifies protease mutations into "Major", "Minor", and "Other", RT mutations into "NRTI", "NNRTI", and "Other" and integrase mutations into "Major", "Minor" and "Other". According to this scheme, "NRTI" and "NNRTI" mutations cannot be further subdivided without the output becoming too unwieldy requiring 5 rather than 3 categories. Moreover, the original sub-classification of mutations into "Major" and "Minor" categories began with the PIs and so most HIV drug resistance researchers and clinicians are comfortable with this classification scheme.

Make sure to process the mutations when writing the JSON into these classifications, which depends on their location. There isn't a readily-available dataset that allows for this. I either have to scrape the HIVdb website ([example](https://hivdb.stanford.edu/pages/documentPage/PI_mutationClassification.html)) or find a way to do it using the current XML-based algo.

**Comment by ArtPoon** [comment]
Ok to scrape major/minor classifications from website - in fact, not worth doing actual scraping, copypaste is fine.  Generate dictionary of mutation-to-drug mapping from rule set in algorithm XML.

**Comment by jzpero** [comment]
Done for:
- [x] IN (2dbe2b5a49551fcb67f88efc6e37bb2c8691d7c0)
- [ ] PI 
- [ ] RT

**Comment by jzpero** [comment]
Pulled data from HIVdb website
