### ISSUE TITLE
Validation status

### ISSUE THREAD

**Issue by jzpero** [PoonLab/sierra-local#15]
Using the testing script, I ran ~1000 consecutive sequences from HIVdb of each of PR, IN, RT on both sierra-local and sierrapy, and compared the outputs:

Gene | Absolute Match Ratio
-|-
PR | 0.983
IN | 1.000
RT | 0.950

Remaining issues are related to polymorphisms and idiosyncrasies in how sierrapy gets its information versus what I get. When an error exists, they are systematically _higher_ than expected by several specific intervals, leading me to suspect that it's the accidental inclusion of a set of specific DRMs in cases where sierrapy would not

**Comment by ArtPoon** [comment]
See issue #11

**Comment by ArtPoon** [comment]
Please generate a list of accession numbers for which we are getting discordant results, so that we can start analyzing the causes.

**Comment by ArtPoon** [comment]
Duplicate of #11
