### ISSUE TITLE
Make GUI with Tkinter?

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#23]
Time permitting.  I've done this before in other Python scripts:
https://github.com/cfe-lab/mixed-hcv/blob/master/mixed-hcv.py
```python
import Tkinter as tk
import ttk
import tkFileDialog

class App:
    def __init__(self, master):
        self.__version__ = '0.1'
        self.master = master
        frame = tk.Frame(master)  # simple container to hold other widgets
        frame.pack()  # resize to contents and make visible
```

**Comment by ArtPoon** [comment]
Look into [Flask](http://flask.pocoo.org/)

**Comment by jzpero** [comment]
# Prototype
## Components
- input file selector
- output file selector
- options panel
- console output (does not output nucamino progress yet... something to do with subprocess stdout or stderr piping)
- run button
- exit button

![image](https://user-images.githubusercontent.com/5045614/40739640-bd4063f0-6414-11e8-842f-9d038430a3b5.png)

**Comment by jzpero** [comment]
I'd actually also like to allow users to paste sequences in to the GUI (pipeline: pasted text -> save as temporary fasta file -> run thru program -> get results -> delete temporary files). Should be a trivial implementation.

See: HIVdb program website, or [Liu 2006](https://dx.doi.org/10.1086%2F503914) Figure 1
![image](https://user-images.githubusercontent.com/5045614/41370097-b248bfa0-6f14-11e8-99c3-292b98cbb6cc.png)
![image](https://user-images.githubusercontent.com/5045614/41370058-8e606bf6-6f14-11e8-9e0f-aaaad52d5766.png)
