### ISSUE TITLE
Generate aligned amino acid sequence from nucleotide sequence input

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#3]
Use ArtPoon/gotoh2 for pairwise alignment to reference
* do Procrustean pairwise alignment (align to reference and discard all positions that are insertions relative to the reference)

**Comment by ArtPoon** [comment]
1. download and install gotoh2
2. write a function that will take a nucleotide sequence as its argument, and return the Procrustean pairwise alignment of that sequence

**Comment by jzpero** [comment]
For translation of the Procrustean aligned nucleotide sequence into aligned amino acids, am I to assume that indels occur in groups of 3 nucleotides as currently assumed in post-align.store_indels()?

And what would the approach be to the reference sequence having insertions relative to the query sequence? Currently, they are left in the alignment, whereas query insertions relative to reference are taken out.

**Comment by ArtPoon** [comment]
If indels are not in groups of 3, then that should be flagged.  However, very rarely a set of indels will occur that sum to a multiple of 3 (e.g., a deletion of 1bp followed by a deletion of 2bp).

If the query has a deletion relative to the reference then they can be left in and passed to the HIVdb algorithm as deletions.

**Comment by ArtPoon** [comment]
No longer an issue since using NucAmino
