### ISSUE TITLE
Sierra-local output file does not match with Sierrapy

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/sierra-local#65]
Output JSON files from both `sierra-local` and `sierrapy` :

[output_files.zip](https://github.com/PoonLab/sierra-local/files/9297732/output_files.zip)

Main differences:

1) Mutation has extra `isApobecMutation`,  `isUnusual`, `isSDRM`, `hasStop`, `primaryType` and `text` fields

<table>
<tr>
<td> <b>sierra-local</b> </td> <td> <b>sierrapy</b> </td>
</tr>
<tr>
<td> 

```json
"mutations": [
  {
      "consensus": "E",
      "position": 6,
      "AAs": "D",
      "isInsertion": false,
      "isDeletion": false,
      "isApobecDRM": false
  },

]
```

</td>
<td>

```json
"mutations": [
    {
      "consensus": "E",
      "position": 6,
      "AAs": "D",
      "isInsertion": false,
      "isDeletion": false,
      "isApobecMutation": false,
      "isApobecDRM": false,
      "isUnusual": false,
      "isSDRM": false,
      "hasStop": false,
      "primaryType": "Other",
      "text": "E6D"
    },
]
```

</td>
</tr>
</table>

2. Addition of the `level` field

<table>
<tr>
<td> <b>sierra-local</b> </td> <td> <b>sierrapy</b> </td>
</tr>
<tr>
<td> 

```json
"drugScores": [
  {
    "drugClass": {
      "name": "NRTI"
    },
    "drug": {
      "name": "ABC",
      "displayAbbr": "ABC"
    },
    "score": 0.0,
    "partialScores": [],
    "text": "Susceptible"
  },
]
```

</td>
<td>

```json
"drugScores": [
  {
    "drugClass": {
      "name": "NRTI"
    },
    "drug": {
      "name": "ABC",
      "displayAbbr": "ABC"
    },
    "score": 0.0,
    "level": 1,
    "partialScores": [],
    "text": "Susceptible"
  },
]
```

</td>
</tr>
</table>

3. Addition of the `SDRMs`, `alignedNAs`, `alignedAAs`, `prettyPairwise` fields

```json
  "SDRMs": [],
  "alignedNAs": "CCAATTAGTCCTATTGACACTGTACCAGTAACATTAAAGCCAGGAATGGATGGACCAAAGGTTAAACAGTGGCCATTGACAGAAGAAAAAATAAAAGCATTAACAGAAATTTGTAAAGAGATGGAAGAGGAAGGAAAAATCTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAGTATTTGCTATAAAGAAAAAGGACAGCACCAAATGGAGGAAATTAGTAGATTTCAGAGAGCTCAATAAAAGAACTCAGGACTTTTGGGAAGTTCAATTAGGAATACCGCATCCAGCAGGTTTAAAAAAGAAAAAATCAGTAACAGTACTAGATGTGGGAGATGCATATTTTTCAGTTCCTTTAGATGAAAGCTTTAGAAAGTATACTGCATTCACCATACCTAGTATAAACAATGAGACACCAGGAATCAGATATCAGTACAATGTGCTGCCACAGGGATGGAAAGGATCACCGGCAATATTCCAGAGTAGCATGACAAAAATCTTAGAGCCCTTTAGAATAAAAAATCCAGAAATGGTTATCTATCAATACAAGGATGACTTGTATGTAGGATCTGATTTAGAAATAGGGCAGCACAGAACAAAAATAGAGGAGCTAAGAGCTCATCTATTGAGCTGGGGATTTACTACACCAGACAAAAAGCATCAGAAGGAACCTCCATTCCTTTGGATGGGATATGAACTCCATCCTGACAGATGGACAGTCCAGCCTATAGAACTGCCAGAAAAAGACAGCTGGACTGTCAATGATATACAGAAATTAGTGGGAAAACTAAATTGGGCAAGTCAAATTTATGCAGGGATTAAGGTAAAGCAACTGTGTAAACTCCTCAGGGGAGCTAAAGCACTAACAGACATAGTACCACTGACTGAAGAAGCAGAATTAGAGTTGGCAGAGAACAGGGAGATTCTAAAAACCCCTGTGCATGGAGTATATTATGACCCATCAAAAGACTTAGTAGCAGAAGTACAGAAACAAGGGCAGGACCAATGGACATATCAAATTTATCAAGAGCCATTTAAAAATCTAAAAACAGGAAAATATGCCAGAAGAGGGTCTGCTCACACTAATGATGTAAGACAATTAACAGAAGTGGTGCAAAAAGTAGCCACAGAAAGCATAGTAATATGGGGAAAGACCCCTAAATTTAGACTACCCATACAAAGAGAAACATGGGAAACATGGTGGATGGAGTATTGGCAGGCTACCTGGATTCCTGAATGGGAGTTTGTTAATACCCCTCCTCTAGTAAAATTATGGTACCAATTAGAAAAAGACCCCATAGTAGGAGCAGAGACTTTCTATGTAGATGGGGCAGCTAGTAGGGAGACTAAGCTAGGAAAAGCAGGGTATGTCACTGACAGAGGAAGACAAAAGGTAGTTTCCCTAACTGAGACAACAAATCAAAAGACTGAATTACATGCGATCCATTTAGCCTTGCAGGATTCAGGATCAGAAGTAAATATAGTAACAGACTCACAATATGCATTAGGAATCATTCAGGCACAACCAGACAGGAGTGAATCAGAAGTAGTCAACCAAATAATAGAGGAGCTAATAAAAAAGGAGAAAGTCTACCTGTCATGGGTACCAGCACACAAGGGGATTGGAGGAAATGAACAAGTAGATAAATTAGTCAGTTCAGGAATCAGGAAGGTGCTA",
  "alignedAAs": "PISPIDTVPVTLKPGMDGPKVKQWPLTEEKIKALTEICKEMEEEGKISKIGPENPYNTPVFAIKKKDSTKWRKLVDFRELNKRTQDFWEVQLGIPHPAGLKKKKSVTVLDVGDAYFSVPLDESFRKYTAFTIPSINNETPGIRYQYNVLPQGWKGSPAIFQSSMTKILEPFRIKNPEMVIYQYKDDLYVGSDLEIGQHRTKIEELRAHLLSWGFTTPDKKHQKEPPFLWMGYELHPDRWTVQPIELPEKDSWTVNDIQKLVGKLNWASQIYAGIKVKQLCKLLRGAKALTDIVPLTEEAELELAENREILKTPVHGVYYDPSKDLVAEVQKQGQDQWTYQIYQEPFKNLKTGKYARRGSAHTNDVRQLTEVVQKVATESIVIWGKTPKFRLPIQRETWETWWMEYWQATWIPEWEFVNTPPLVKLWYQLEKDPIVGAETFYVDGAASRETKLGKAGYVTDRGRQKVVSLTETTNQKTELHAIHLALQDSGSEVNIVTDSQYALGIIQAQPDRSESEVVNQIIEELIKKEKVYLSWVPAHKGIGGNEQVDKLVSSGIRKVL",
  "prettyPairwise": {
    "positionLine": [
    ],
    "refAALine": [
    ],

    "alignedNAsLine": [
    ],
    "mutationLine": [
    ]
```

**Comment by GopiGugan** [comment]
Use [timing.py](https://github.com/PoonLab/sierra-local/blob/iss64/scripts/timing.py) to generate sierrapy output file

**Comment by WilliamZekaiWang** [comment]
Potential explanations for the missing fields, in regards to mutation output, found through analyzing files under:
[sierra-core/src/main/java/edu/stanford/hivdb/mutations/](https://github.com/hivdb/sierra-core/tree/120d685c32bf527cf54a36e8cff9f082ccb9366f/src/main/java/edu/stanford/hivdb/mutations) and [hivdb/hivfacts/data](https://github.com/hivdb/hivfacts/tree/main/data).

- ```isApobecMutation```: a list of APOBEC Mutations found on the [hivdb-database website](https://hivdb.stanford.edu/page/apobecs/) matches the [apobec.json](https://github.com/hivdb/hivfacts/blob/main/data/apobecs/apobecs.json) files found in hivfacts. 
  - Potential fix: check if the mutation at a certain gene, position, and resulting amino acid matches any of the listed ones under the APOBEC JSON file, and if it does return True.

- ```isUnusual```: Under the datafiles section, Unusual mutations, on the [hivdb-database website](https://hivdb.stanford.edu/page/release-notes/#data.files) shows the following [CSV file](https://raw.githubusercontent.com/hivdb/hivfacts/2021.3/data/aapcnt/rx-all_subtype-all.csv). The boolean values for isUnusual in the CSV match the JSON file, [mutation-type-pairs_hiv1.json](https://github.com/hivdb/hivfacts/blob/main/data/mutation-type-pairs_hiv1.json) and [mutation-type-pairs_hiv1.json](https://github.com/hivdb/hivfacts/blob/main/data/mutation-type-pairs_hiv2.json) found in hivfacts.
  - Potential fix: check if the gene, position, and amino acid of the mutation are in mutation-type-pair files, then return the boolean value associated with isUnusual.

- ```isSDRM```: The compilation of the SDRM resulting mutation on the [hivdb-stanford website for surveillance mutations] matches with [sdrm_hiv1](https://github.com/hivdb/hivfacts/blob/main/data/sdrms_hiv1.json) and [sdrm_hiv2](https://github.com/hivdb/hivfacts/blob/main/data/sdrms_hiv2.json) in hivfacts/data.
  - Potential fix: check if the gene, position, and amino acid of the mutation are in the two sdrms_hiv files, and return True if match.

- ```isPrimaryMutations```: in the [AAMutation.java file](sierra-core/src/main/java/edu/stanford/hivdb/mutations/AAMutation.java), isPrimaryMutation seems to just call for "mutation type", which is found the same file with the boolean values of isUnusual in [mutation-type-pairs_hiv1.json](https://github.com/hivdb/hivfacts/blob/main/data/mutation-type-pairs_hiv1.json) and [mutation-type-pairs_hiv1.json](https://github.com/hivdb/hivfacts/blob/main/data/mutation-type-pairs_hiv2.json)
  - Potential fix: when calling for the isUnusual from the JSON files, also get the value for mutationType

- ```hasStop```: checks if the resulting mutation results in a stop codon

- ```Text```: output is the concatenation of ```consensus``` ```position``` ```AAs``` outputs in that order

**Comment by WilliamZekaiWang** [comment]
Comparing results to sierrapy output with the test fasta file with JSON files in hivdb

```isApobecMutation```  when true, always matches with a mutation listed in [apobec.json](https://github.com/hivdb/hivfacts/blob/main/data/apobecs/apobecs.json)

```isSDRM``` is in the same case with isApobecMutation as it always matched with [sdrms_hiv](https://github.com/hivdb/hivfacts/blob/main/data/sdrms_hiv1.json)

```primaryType``` seems to hold true too with [mutation-type-pairs.json](https://github.com/hivdb/hivfacts/blob/main/data/mutation-type-pairs_hiv1.json)

```isUnusual``` was not consistent with the JSON files, but was with the CSV file. Seems like the CSV file had more entries than the JSON, and if a singular AA matched with the csv file for True it would return True.

**Comment by WilliamZekaiWang** [comment]
The ordering of Amino Acids in mutations for sierrapy and sierra-local isn't always consistent in the order they are written
| Sierrapy                                                                                                                                                                                                                                        | Sierra-Local                                                                                                                           |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| { <br/>"consensus": "D", <br/>"position": 185, <br/>"AAs": "DE", <br/>"isInsertion": false, <br/>"isDeletion": false, <br/>"isApobecMutation": false, <br/>"isApobecDRM": false, <br/>"isUnusual": true, <br/>"isSDRM": false, <br/>"hasStop": false, <br/>"primaryType": "Other", <br/>"text": "D185DE" <br/>}, | { <br/>"consensus": "D", <br/>"position": 185, <br/>"AAs": "ED", <br/>"isInsertion": false, <br/>"isDeletion": false, <br/>"isApobecDRM": false, <br/>"text": "D185ED"<br/> }, |

Where in sierra-local it states ED instead of DE

**Comment by WilliamZekaiWang** [comment]
Sorting the AAs seemed to fix the issue above. 

All mutations fields seem to work except `primaryType` and `isUnusual`. Going to try with the CSV file on the hivdb download page

**Comment by WilliamZekaiWang** [comment]
Seems to work with the [csv file] (https://hivdb.stanford.edu/page/release-notes/#data.files)
Adding `SDRMs`, `alignedNAs`, `alignedAAs`, `prettyPairwise`, seems as they are just outputting already analyzed data

**Comment by ArtPoon** [comment]
Converting CSV into a nested dictionary is always faster than linear search:
```python
import csv
rx = {}
reader = csv.DictReader(open("rx-all_subtype-all.csv", encoding='utf-8-sig'))

for row in reader:
    gene = row['gene']
    pos = row['position']
    aa = row['aa']
    unusual = row['isUnusual']
    if gene not in rx:
        rx.update({gene: {}})
    if pos not in rx[gene]:
        rx[gene].update({pos: {}})
    rx[gene][pos].update({aa: unusual})
```

**Comment by WilliamZekaiWang** [comment]
All fields have been added and seem to be working. `positionLine` was created by taking the first and last AA positions and making a list with all values in between. This is working with the RT.file.

`primaryType` detects when the mutation isn't just "other" when compared to the associated file in HIVfacts but returns an incorrect response for which drug.

There also seem to be more fields missing
<table>
<tr>
<td> Sierralocal</td> <td> Sierrapy</td>
</tr>
<tr>
<td> 

```
{
    "inputSequence": {
      "header": "U54771.CM240.CRF01_AE.0"
    },
    "subtypeText": "",
    "validationResults": [],
```

</td>
<td>


```
[
  {
    "inputSequence": {
      "header": "U54771.CM240.CRF01_AE.0",
      "SHA512": "873aa696499f3eaba28a2e39853afbe337373222913d13d4030d2b2cfb8bdf7acb81b98fab1019e48d9daea263e78a7f1a685eac42bc337c38ebc8a92e019325"
    },
    "strain": {
      "name": "HIV1"
    },
    "subtypeText": "CRF01_AE (0.65%)",
    "validationResults": [
      {
        "level": "NOTE",
        "message": "There is one unusual mutation at a drug-resistance position in RT: M184K."
      }
    ],
```


</td>
</tr>
</table>
Addition of the `SHA512`, `strain` and `name` fields

Sierralocal also does not seem to output the same `validation results` with the appropriate `message` and `level`

**Comment by WilliamZekaiWang** [comment]
I was checking with HIV2A/B mutations rather than HIV1 for `validationResults`, it seems to be fine

**Comment by WilliamZekaiWang** [comment]
When there is an `validationResults` output for sierrapy with the statement "... positions were not sequenced or aligned", sierralocal incorrectly assumes one extra AA
``` diff
<     "validationResults": [],
---
>     "validationResults": [
>       {
>         "level": "WARNING",
>         "message": "203 positions were not sequenced or aligned: RT 358-560. However, none is at drug-resistance position."
>       }
>     ],
5c10
<         "lastAA": 358,
---
>         "lastAA": 357,
8,9c13,16
<           "length": null
<         },
\ No newline at end of file
---
>           "length": 560
>         },
>         "mutations": [
>           {
```

**Comment by WilliamZekaiWang** [comment]
sha512 output converted was the NA sequence in the sequences inputted

**Comment by ArtPoon** [comment]
Please manually compare the raw sequences that are reported to have different lengths.
Is the extra character due to an invisible Unicode symbol?

**Comment by ArtPoon** [comment]
For classifying input sequences into HIV-1 versus HIV-2, we might need to use their pairwise alignment method (nucamino) to align each input sequence to a consensus genome sequence of each "strain" and count differences for a crude distance measure, and classify accordingly.
Let's put this off as a separate issue.

**Comment by ArtPoon** [comment]
Make validation a separate issue.

**Comment by WilliamZekaiWang** [comment]
an issue with AAs output in mutations from sierralocal and sierrapy. Sequences are the sequences from the test RT file

Sequence: AF090509.260Pt28BC.B.12
```
Sierra Local {'consensus': 'T', 'position': 27, 'AAs': 'X',

Sierrapy {'consensus': 'T', 'position': 27, 'AAs': 'IKMNRST',
```
Sequence: AF021275.JIDP16W0.B.15 
```
Sierra local {'consensus': 'K', 'position': 220, 'AAs': 'X'

Sierrapy  {'consensus': 'K', 'position': 220, 'AAs': '*ACDEFGHIKLMNPQRSTVWY'
```
Sequence: AF021280.JIDP7W0.B.16 
```
Sierra local {'consensus': 'K', 'position': 219, 'AAs': 'X'

Sierrapy  {'consensus': 'K', 'position': 219, 'AAs': 'IKMNRST'
```

**Comment by ArtPoon** [comment]
See if updating the `nucamino` binaries resolves this

**Comment by WilliamZekaiWang** [comment]
The X amino acid problem still persists in post-align, perhaps it's not an issue with the alignment program but the way we are interpreting indels, as we immediately categorize them as X.

**Comment by ArtPoon** [comment]
@WilliamZekaiWang to merge `dev` branch into `postalign` to see if this resolves the above issue, then do a PR from `postalign` to `dev` and complete this issue in the `dev` branch.
