### ISSUE TITLE
Scoring algorithm results not matching with HIVdb output

### ISSUE THREAD

**Issue by jzpero** [PoonLab/sierra-local#8]
The current implementation with HXB2 pol test sequence
`jasper@asus:~/git/sierra-local$ python sierra-local.py -i hxb2pol.fasta`
results in the following:
`{'ETR': 10, 'didanosine': 10, 'abacavir': 5, 'DTG': 5, 'EVG': 10, 'saquinavir/r': 75, 'nevirapine': 60, 'rilpivirine': 10, 'DRV/r': 30, 'SQV/r': 75, 'lopinavir/r': 90, 'AZT': 20, 'IDV/r': 90, 'atazanavir/r': 90, 'indinavir/r': 90, '3TC': 0, 'fosamprenavir/r': 75, 'FPV/r': 75, 'lamivudine': 0, 'TPV/r': 105, 'etravirine': 10, 'D4T': 20, 'ABC': 5, 'raltegravir': 60, 'tenofovir': 5, 'emtricitabine': 0, 'stavudine': 20, 'EFV': 60, 'NFV': 90, 'DDI': 10, 'nelfinavir': 90, 'dolutegravir': 5, 'tipranavir/r': 105, 'elvitegravir': 10, 'LPV/r': 90, 'NVP': 60, 'FTC': 0, 'RPV': 10, 'TDF': 5, 'zidovudine': 20, 'ATV/r': 90, 'efavirenz': 60, 'darunavir/r': 30, 'RAL': 60}`

Compared to the output from HIVdb, these scores are higher than the predicted resistances:
![image](https://user-images.githubusercontent.com/5045614/32395221-95b67826-c0b6-11e7-8479-2208f86f8c55.png)

`sierrapy` gives the correct output.

Double checked this with just score_alg.py, just in case this was an issue with my implementation. Will take a closer look this weekend.

**Comment by ArtPoon** [comment]
Thanks.  Other things to check:
* alignment of sequence, is it different?
* are there relevant insertions, deletions?
* how are we handling ambiguous bases, *i.e.,* mixtures?

**Comment by jzpero** [comment]
Fixed an issue with the alignment, and narrowed that issue down. Now able to generate correct scores for SOME drugs. There's an issue with the scoring algorithm somewhere:

**Example 1**
HIVdb results for accession #AY030621 protease sequence grabbed from HIVdb:

PI | ATV/r | DRV/r | FPV/r | IDV/r | LPV/r | NFV | SQV/r | TPV/r
-- | -- | -- | -- | -- | -- | -- | -- | --
G73S | 10 | 0 | 10 | 15 | 5 | 15 | 15 | 0
L90M | 25 | 0 | 20 | 30 | 15 | 60 | 45 | 0
G73S + L90M | 10 | 0 | 10 | 10 | 0 | 10 | 10 | 0
Total | 45 | 0 | 40 | 55 | 20 | 85 | 70 | 0

Results from the current implementation (formatted):

ATV/r | DRV/r | FPV/r | IDV/r | LPV/r | NFV | SQV/r | TPV/r
-- | -- | -- | -- | -- | -- | -- | --
25 | 0 | 20 | 30 | 15 | 60 | 45 | 0

Only L90M is being picked up.

**Example 2**
HIVdb results for accession #KU127836 RT sequence grabbed from HIVdb:

NRTI | ABC | AZT | FTC | 3TC | TDF
-- | -- | -- | -- | -- | --
M41L | 5 | 15 | 0 | 0 | 5
V75I | 5 | 5 | 5 | 5 | 5
M184V | 15 | -10 | 60 | 60 | -10
T215Y | 10 | 40 | 0 | 0 | 10
M41L + T215Y | 15 | 10 | 5 | 5 | 10
Total | 50 | 60 | 70 | 70 | 20


NNRTI | EFV | ETR | NVP | RPV
-- | -- | -- | -- | --
A98G | 15 | 10 | 30 | 15
Y181C | 30 | 30 | 60 | 45
H221Y | 10 | 10 | 15 | 15
A98G + Y181C | 5 | 5 | 5 | 5
Total | 60 | 55 | 110 | 80

Compare this to the results from current implementation:

ABC | AZT | FTC | 3TC | TDF
-- | -- | -- | -- | --
20 | 5 | 65 | 65 | 5

Does not match

EFV | ETR | NVP | RPV
-- | -- | -- | --
 60  | 55 | 110 | 80

Matches

I can't find any obvious patterns with which scores are being included/excluded in the NRTIs

**Comment by ArtPoon** [comment]
For AY030621:  when I translate the sequence, I note there are mixtures at residue 72 and RT197 (296).  I think this might explain why we're missing the result with G73S.  There's something wrong with the `return_list` functionality of `translate_nuc`.

**Comment by jzpero** [comment]
Wasn't `translate_nuc` per se, but something with the algorithm not considering mixed residues and the way we approached the scoring. Circumvented using `NucAmino`, and the scores are now matching for every drug (needs more validation, though).
