### ISSUE TITLE
Test coverage improvement issue for `get_closest_subtype` function of `subtyper.py`

### ISSUE THREAD

**Issue by SandeepThokala** [PoonLab/sierra-local#80]
https://github.com/PoonLab/sierra-local/blob/707db8e8b1ab51f89ea1a1c29a5baa96ed61c12e/sierralocal/subtyper.py#L123-L130

```The function always stops at line 127 and rest of the lines (128 - 164) never get any coverage```

https://github.com/PoonLab/sierra-local/blob/707db8e8b1ab51f89ea1a1c29a5baa96ed61c12e/sierralocal/subtyper.py#L152-L164

**Comment by ArtPoon** [comment]
* one place to check is here:
https://github.com/PoonLab/sierra-local/blob/master/sierralocal/data/genotype-properties.cc00f512.csv
are the percentages being parsed correctly?
* this file has not been updated in a long, long time!

**Comment by ArtPoon** [comment]
@SandeepThokala can you check whether this function has been deprecated in the hivdb version?  If so we can just deactivate this test.

**Comment by SandeepThokala** [comment]
Deactivating the test
