### ISSUE TITLE
Missing required dependencies: cython==0.29.32, postalign @ https://github.com/hivdb/post-align

### ISSUE THREAD

**Issue by Kanyerezi30** [PoonLab/sierra-local#84]
Hello Team

I have followed the procedure to download the new repo but I get the error below yet have installed both dependencies

`Missing required dependencies: cython==0.29.32, postalign @ https://github.com/hivdb/post-align`

**Comment by Kanyerezi30** [comment]
`
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
`
For python: 
`
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
`

**Comment by WilliamZekaiWang** [comment]
Hi,

I thought I updated the readme to reflect the Python version I tested it on, which was `3.10.9` and `3.9.0`, but it seems like I didn't. I'm sorry for that.

If possible could you try updating the python version to at least 3.9 and then reinstalling cython?

**Comment by GopiGugan** [comment]
Hi @Kanyerezi30, can you also please confirm you installed version `0.29.32` of cython?

**Comment by Kanyerezi30** [comment]
Thank you

I have got it running. Though I realise that the option of specifying the apobec mutations was dropped

**Comment by GopiGugan** [comment]
> I have got it running. Though I realise that the option of specifying the apobec mutations was dropped

We used to accept the HIVdb APOBEC DRM file in tsv format:
https://github.com/PoonLab/sierra-local/blob/6977b806aa92afa74697edccf3c1c9ccedc9c77c/sierralocal/main.py#L155-L156

But we now read in the file in JSON format:
https://github.com/PoonLab/sierra-local/blob/b0b6dea60eefe661f38c852e5a22c2c3e1329f3d/sierralocal/main.py#L167-L168

Can you please try again with a JSON file?

**Comment by WilliamZekaiWang** [comment]
I have found the error with why specifying `apobec mutations` doesn't work anymore, it seems like it was a bug with the recent PR which I think I have fixed in the dev branch

**Comment by mbyott** [comment]
Hi, I have same issue:
`Missing required dependencies: cython==0.29.32, postalign @ https://github.com/hivdb/post-align`

`Ubuntu 22.04` and `Python 3.10.12`.

I get no errors when running the `pip install` command for post align.
I've also used` pip install Cython --install-option="--no-cython-compile"` to check Cython is installed correctly.

**Comment by WilliamZekaiWang** [comment]
Hi, 

`postalign` has been giving us issues recently, but that command likely suggests that either `cython` or `post-align` was not properly installed. One thing I can suggest is running the `pip install` directly after extracting the post-align zip file, which sometimes solved the issue for me

```
wget https://github.com/hivdb/post-align/archive/3f99cc81ad89d66adf3beb062c93962f0deb3352.zip
unzip 3f99cc81ad89d66adf3beb062c93962f0deb3352.zip
cd post-align-3f99cc81ad89d66adf3beb062c93962f0deb3352
pip install .
```

If you still get the issue and the requirements are properly installed, you can comment out the following lines in `setup.py` to force the program to run. 
https://github.com/PoonLab/sierra-local/blob/b0b6dea60eefe661f38c852e5a22c2c3e1329f3d/setup.py#L11-L32
