### ISSUE TITLE
Subtyping

### ISSUE THREAD

**Issue by Kanyerezi30** [PoonLab/sierra-local#85]
Hello here

The updated version doesn't do the subtyping automatically. I had to locate the subtyper.py script and executed it to get the subtype

Is it possible to have the functionality run automatically within the sierralocal command

**Comment by WilliamZekaiWang** [comment]
I have made it a feature in the dev branch, by calling `-subtype` in the terminal alongside `sierralocal` it should call on the `subtype.py` script on the file.
