### ISSUE TITLE
Incorporate Stanford HIVDB's NucAmino aligner?

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#9]
https://github.com/hivdb/NucAmino

It's written in the Go programming language, with the option of using a Docker container..

**Comment by jzpero** [comment]
Implemented (roughly) using `subprocess` and resulting `.tsv` output parsing. Used the compiled binary of nucamino.
df9bd6c66df2686c2a2239b8ce46c46d1fb39299

**Comment by jzpero** [comment]
Easier to work with in this context than gotoh2 + manual translation, as it's the hivdb implementation.

**Comment by ArtPoon** [comment]
Sounds good.  My only concern is how portable the binary is going to be.

**Comment by philiptzou** [comment]
Hi, I'm the author of NucAmino. I'd like to say thanks for using the program. Please feel free to report issues and feedbacks to me at here: https://github.com/hivdb/nucamino/issues.
