### ISSUE TITLE
Missing T69S_SS (T69ins) mutation

### ISSUE THREAD

**Issue by Kanyerezi30** [PoonLab/sierra-local#91]
Hello here

It seems sierralocal misses the T69S_SS (T69ins) mutation - an nrti mutation which contributes to the level of resistance for NRTI drugs

Any help is much appreciated

**Comment by WilliamZekaiWang** [comment]
Hi,

I think this issue may arise because of an outdated file. Could you `sierralocal\updater.py` script? That script should update you to the `HIVDB_9.5.0.xml` file which holds relevant information.

**Comment by Kanyerezi30** [comment]
Thanks

We shall look into this in-depth and revert

**Comment by Kanyerezi30** [comment]
We haven't yet figured out where the problem comes from as updating the XML didn't solve the issue

**Comment by ArtPoon** [comment]
@WilliamZekaiWang can you please take a test RT sequence, manually add this insertion and run it through sierra-local to see if we can reproduce this issue?

**Comment by WilliamZekaiWang** [comment]
I have recreated this issue.

I manually added serine to one of the RT files at position 69 and it did not get picked up to increase NRTI score resistance.

I tested this again using `NNN` on the reference sequence, ignoring the changes made for #92, and it did pick it up. Not as an insertion, but rather as `T69D`, which is an incorrect assumption for `NNN`

**Comment by WilliamZekaiWang** [comment]
This insertion is picked up in sierrapy and it is correctly identified as an NRTI mutation. I believe the issue is that we're missing an output from post-align that signifies the mutation is an insertion.

**Comment by WilliamZekaiWang** [comment]
I got post-align's output and it seems to indicate if the mutation is an insertion or not:
```
            {
              "Position": 69,
              "RefCodonText": "ACT",
              "CodonText": "NNN",
              "RefAminoAcidText": "T",
              "AminoAcidText": "*ACDEFGHIKLMNPQRSTVWY",
              "InsertedCodonsText": "ACC",
              "IsInsertion": true,
              "IsDeletion": false
            },
```
It looks like it's not being piped into the drug mutation calculations, because our report is:
```
          {
            "consensus": "T",
            "position": 69,
            "AAs": "*ACDEFGHIKLMNPQRSTVWY",
            "isInsertion": false,
            "isDeletion": false,
            "isApobecMutation": false,
            "isApobecDRM": false,
            "isUnusual": false,
            "isSDRM": true,
            "hasStop": false,
            "primaryType": "Other",
            "text": "T69X"
          },```

**Comment by WilliamZekaiWang** [comment]
I think I have fixed the issue on the dev branch. 

Now, when we have an insertion mutation at position 69, it should catch it

example below
```
                    "text": "T69i",
                    "primaryType": "NRTI",
                    "comments": [
                      {
                        "type": "NRTI",
                        "text": "Amino acid insertions between codons 67 and 70 are by convention assigned to codon 69. Together with TAMs, they are associated with high-level resistance to AZT, ABC and TDF, and intermediate to 3TC and FTC."
                      }
```

**Comment by ArtPoon** [comment]
Thanks for catching this @WilliamZekaiWang - can you please issue a PR when you have time?
