### ISSUE TITLE
JSON to CSV conversion Error: json2csv.py

### ISSUE THREAD

**Issue by gpcr** [PoonLab/sierra-local#94]
python3 /sierra-local/scripts/json2csv.py /hiv/Fastq/Test_001.report.json Test_001_001.report.json.csv

```python

 /sierra-local/scripts/json2csv.py", line 42, in <module>
    json2csv(infile=args.json, outfile=args.csv)
  File "/sierra-local/scripts/json2csv.py", line 14, in json2csv
    for d in result['drugResistance']:
TypeError: string indices must be integers
```

**Comment by ArtPoon** [comment]
@WilliamZekaiWang can you please try reproducing this problem?
@gpcr can you please provide version information?

**Comment by gpcr** [comment]
@WilliamZekaiWang I using the report.Json generated by sierrapy using the codfreq

sierrapy seqreads test.codfreq -q hiv1_sequence_reads_analysis_default.gql

**Comment by WilliamZekaiWang** [comment]
Hi,

I have managed to duplicate the error.

However, I don't believe the `json2csv.script` was made for the `sierrapy seqreads` output. I believe the original script was made to turn the fasta file output from either `sierralocal fasta.fa` or `sierrapy fasta fasta.fa`.

I've tried the `json2csv.script` from the fasta output of sierrapy and sierralocal and they both worked

**Comment by gpcr** [comment]
Thanks for the update @WilliamZekaiWang , any suggestions for using seqreads output conversion?

**Comment by ArtPoon** [comment]
Hi @gpcr - converting between seqread format and other formats is not covered by sierra-local and unfortunately we do not have the bandwidth to do this right now, sorry.  Closing issue.
